[package]
name = "spid-rocket"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"

[lib]
name = "spid"
path = "lib/spid.rs"

[[bin]]
name = "spid-rocket"
path = "src/main.rs"
